### PR TITLE
675 dont show failed expectations when errored

### LINKED ISSUE #675: Don't show failed expectations when status is errored
Because it doesn't make sense: we couldn't even run the expectations because the code is wrong.

### PR DESCRIPTION
**Pull request by aguspina**
Fixes #675

### CODE REVIEW

File: app/models/assignment.rb [hunk 1]
```diff
@@ -40,7 +40,7 @@ def feedback_html
   end
 
   def expectation_results_visible?
-    visible_expectation_results.present?
+    visible_expectation_results.present? && !errored?
```
Comment (flbulgarelli) [inline app/models/assignment.rb]: Could we add a test for this?

Comment (aguspina) [inline app/models/assignment.rb]: @flbulgarelli check it now!
